config/routes.rb
Rails3BackboneCoffeescript::Application.routes.draw do
  devise_for :users
  
  resources :projects
  
  root :to => "projects#index"
  

end

app/models/project.rb
class Project
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  respond_to :html, :json
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_flash.html.haml
#flash-messages
  - unless notice.blank?
    .notice
      .container
        %p= notice

  - unless alert.blank?
    .alert
      .container
        %p= alert

app/views/layouts/_header.html.haml
#header
  .container
    #logo
      %h1 rails3-backbone-coffeescript
    #nav
      %ul
        %li= link_to "home", root_path
        - if user_signed_in?
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Sign out", destroy_user_session_path
        - else
          %li= link_to "Login", new_user_session_path
    .clearfix

app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %title Example
    = include_stylesheets :common
    = include_javascripts :common, :application
    = csrf_meta_tag

  %body
    = render :partial => "/layouts/header"
    
    = render :partial => "/layouts/flash"
    
    #main
      .container
        = yield
      
    #footer
      .container
        footer

app/views/projects/_form.html.haml
= form_for @project do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
#projects
  / %h1 Listing projects
  / 
  / %table
  /   %tr
  /     %th Name
  /     %th Description
  /     %th
  /     %th
  /     %th
  / 
  /   - @projects.each do |project|
  /     %tr
  /       %td= project.name
  /       %td= project.description
  /       %td= link_to 'Show', project
  /       %td= link_to 'Edit', edit_project_path(project)
  /       %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete
  / 
  / %br
  / 
  / / = link_to 'New Project', new_project_path
  / = link_to 'New Project', "#/new"

:javascript
  window.controller = new App.Controllers.ProjectsController({projects: #{@projects.to_json}});
  Backbone.history.start();

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project.name
%p
  %b Description:
  = @project.description

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>